server:
  shutdown: immediate

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    enabled: true
    contexts: local
    change-log: classpath:/db/changelog-master.xml

application:
  scheduler:
    enabled: true