@Library('meshkorea') _

vroongMsaJava17MultiPipeline(
    team: '',
    ecrRepoName: 'vroong/{{projectName}}',
    argoAppName: 'vroong-{{projectName}}',
    gradleBuildArguments: '-x :clients:build'
)
