server:
  port: {{portNumber}}

spring:
  profiles:
    active: local

  output:
    ansi:
      enabled: always

  r2dbc:
    url: r2dbc:mysql://localhost:3306/local_{{projectName}}?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: secret

  security:
    oauth2:
      client:
        registration:
          uaa:
            client-id: internal
            client-secret: internal
            scope: web-app
            authorization-grant-type: client_credentials
        provider:
          uaa:
            token-uri: http://localhost:9999/oauth/token
            jwk-set-uri: http://localhost:9999/.well-known/jwks.json

  cloud:
    function:
      definition: consumeMessage
    stream:
      bindings:
        # CONVENTIONS: https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_functional_binding_names
        #   <functionName> + -in- + <index>
        #   <functionName> + -out- + <index>
        # Consumer properties: https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_consumer_properties
        # Producer properties: https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_producer_properties
        consumeMessage-in-0:
          group: {{projectName}}-comsumer-group
          destination: local-{{projectName}}-output
        produceMessage-out-0:
          destination: local-{{projectName}}-output
          header-mode: headers
      binders:
        kafka:
          type: kafka
          headers: [ "messageId", "messageType", "messageVersion", "messageSource" ]
      default-binder: kafka

  sleuth:
    web.additional-skip-pattern: '/management/.*'

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["health", "info"]
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  info:
    git:
      mode: simple
  health:
    mail.enabled: false

sentry:
  release: #project.version#
  in-app-includes: '{{packageName}}'
  enable-tracing: 'true'
  traces-sample-rate: '0.001'

application:
  version: #project.version#
  scheduler:
    enabled: false
